name: Publish With Single Worker

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - README.md
      - .github/workflows/publish_test.yml.BAK

env:
  REGISTRY_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/unbound-test

jobs:
  Docker-Build-Single:
    strategy:
      matrix:
        include:
          - version: 1.17.1
            tags: latest
          - version: 1.17.1
            tags: 1.17.1
          - version: 1.17.0
            tags: 1.17.0
          - version: 1.16.3
            tags: 1.16.3
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.version }}
          platforms: linux/amd64, linux/arm64/v8
          push: true
          tags: "${{ env.REGISTRY_IMAGE }}:${{ matrix.tags }}"
